### ISSUE TITLE
mathlink path rename on Windows?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaInterop/MathLink.jl#30]
It works for me when I use `ml64i4.dll`, which is different from what's mentioned in the README. Does it need to be updated? The one in the README doesn't exist in my Wolfram Engine installation.

**Comment by crstnbr** [comment]
Same for me.

**Comment by simonbyrne** [comment]
Apologies for the late reply: It turns out I had unsubscribed myself from the repository.

@ChrisRackauckas and @crstnbr: can you checkout master and see if it works correctly now?

By the way, could someone on Windows also figure out if the installation path is in the registry somewhere? Some googling suggests it stores some info in
```
HKEY_CURRENT_USER\Software\Wolfram Research\Mathematica
```
If the installation path is there, then we can just use that.

**Comment by zwwi** [comment]
> By the way, could someone on Windows also figure out if the installation path is in the registry somewhere? Some googling suggests it stores some info in
> HKEY_CURRENT_USER\Software\Wolfram Research\Mathematica
> 

not in my case.
